version: '3.8'

services:
  # camunda:
  #   image: camunda/camunda-bpm-platform
  #   ports: "8080:8080"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - my-networks
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: 'kafka-internal.io'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-internal.io
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - my-networks
  worker:
    build: ./worker/
    depends_on:
      - kafka
    links:
      - "kafka:kafka"
    environment:
      KAFKA_CONNECT: kafka:9092
    networks:
      - my-networks
  lambda-1:
    build: ./lambda-1/
    depends_on:
      - worker
    links:
      - "kafka:kafka"
    environment:
      KAFKA_CONNECT: kafka:9092
    networks:
      - my-networks
networks:
  my-networks:
    driver: bridge