version: '3.8'

services:
  # camunda:
  #   image: camunda/camunda-bpm-platform
  #   ports: "8080:8080"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  # kafdrop:
  #   image: obsidiandynamics/kafdrop 
  #   environment:
  #     # KAFKA_BROKERCONNECT: "localhost:9092"
  #     JVM_OPTS: "-Xms32M -Xmx64M"
  #     SERVER_SERVLET_CONTEXTPATH: "/"